baseURL = 'https://calexo-metacorp.github.io/web/'
languageCode = 'en-us'
title = ''
theme = 'hugo-coder'

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "calexo"

[params]
  author = "calexo"
  # info = "General"
  description = "Calexo"
  keywords = "Proofreading, Copyediting, Editing, Grammar, Spelling, Punctuation, Accuracy, Attention to detail, Language skills, Writing skills, Translation, Bilingual, Language skills, Interpreter, Localization, Multilingual, Proofreading, Editing, Interpretation, Language proficiency, Star Atlas, Metaverse, NFTs, Crypto, Gaming, Virtual worlds, Blockchain, Spaceships, Exploration, Space economy, Storytelling, Creative writing, Children's stories, Fiction, Oral storytelling, Narration, Public speaking, Literature, Imagination, Story development, Writing, Author, Creative writing, Fiction, Non-fiction, Book writing, Freelance writing, Ghostwriting, Content creation, Manuscript development"

  since = 2023

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

  [taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Telegram"
  icon = "fa fa-paper-plane fa-2x"
  weight = 3
  url = "https://t.me/calexo"

[[params.social]]
  name = "Whatsapp"
  icon = "fa fa-whatsapp fa-2x"
  weight = 3
  url = "https://wa.me/message/DLFO4QZRVPMKN1"

[[routes]]
  path = "/budget-request"
  file = "budget-request.html"
